CREATE TABLE Races (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Race_Name VARCHAR(255) NOT NULL,
    Date DATETIME NOT NULL,
    Location VARCHAR(255) NOT NULL
);

CREATE TABLE Teams (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Team_Name VARCHAR(255) NOT NULL,
    Team_Principal VARCHAR(255) NOT NULL
);

CREATE TABLE Drivers (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Team_ID INTEGER NOT NULL,
    Driver_Name VARCHAR(255) NOT NULL,
    FOREIGN KEY (Team_ID) REFERENCES Teams(ID)
    ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE PitStops (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Race_ID INTEGER NOT NULL,
    Driver_ID INTEGER NOT NULL,
    Pitstop_Time DATETIME NOT NULL,
    FOREIGN KEY (Race_ID) REFERENCES Races(ID)
    ON DELETE CASCADE ON UPDATE NO ACTION,
    FOREIGN KEY (Driver_ID) REFERENCES Drivers(ID)
    ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE Laps (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Race_ID INTEGER NOT NULL,
    Driver_ID INTEGER NOT NULL,
    Lap_Time DATETIME NOT NULL,
    FOREIGN KEY (Race_ID) REFERENCES Races(ID)
    ON DELETE CASCADE ON UPDATE NO ACTION,
    FOREIGN KEY (Driver_ID) REFERENCES Drivers(ID)
    ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE Standings (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Race_ID INTEGER NOT NULL,
    Driver_ID INTEGER NOT NULL,
    Position INTEGER NOT NULL,
    Points INTEGER NOT NULL,
    FOREIGN KEY (Race_ID) REFERENCES Races(ID)
    ON DELETE CASCADE ON UPDATE NO ACTION,
    FOREIGN KEY (Driver_ID) REFERENCES Drivers(ID)
    ON DELETE CASCADE ON UPDATE NO ACTION
);
